name: angular_app
description: A web app that uses AngularDart
version: 0.0.1

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  angular: ^5.0.0
  http: ^0.11.0
  stream_transform: ^0.0.6            
  angular_router: ^2.0.0-alpha+19
  angular_components: ^0.9.2
angular_forms: ^1.0.0  
  
  

dev_dependencies:
  build_runner: ^0.10.0
  build_test: ^0.10.2
  build_web_compilers: ^0.4.0
  test: ^1.0.0
